import fs from 'fs';
import path from 'path';
import http from 'http';
import handler, { app } from '../../api/index';

async function runVercelDeploymentTests() {
  console.log('\n============================================================');
  console.log('       RUNNING VERCEL DEPLOYMENT ARCHITECTURE TESTS         ');
  console.log('============================================================');

  let passed = 0;
  let failed = 0;

  function assert(condition: boolean, name: string, detail?: string) {
    if (condition) {
      console.log(`  \x1b[32m[PASS]\x1b[0m ${name}`);
      passed++;
    } else {
      console.log(`  \x1b[31m[FAIL]\x1b[0m ${name}${detail ? ` - ${detail}` : ''}`);
      failed++;
    }
  }

  // 1. Check vercel.json
  const vercelJsonPath = path.join(process.cwd(), 'vercel.json');
  assert(fs.existsSync(vercelJsonPath), '[Config] vercel.json file exists at project root');

  if (fs.existsSync(vercelJsonPath)) {
    try {
      const vercelConfig = JSON.parse(fs.readFileSync(vercelJsonPath, 'utf-8'));
      assert(Array.isArray(vercelConfig.rewrites), '[Config] vercel.json has rewrites array');
      
      const apiRewrite = vercelConfig.rewrites.find((r: any) => r.source === '/api/(.*)' && r.destination === '/api');
      assert(!!apiRewrite, '[Routing] vercel.json routes /api/(.*) -> /api serverless function');

      const spaRewrite = vercelConfig.rewrites.find((r: any) => r.destination === '/index.html');
      assert(!!spaRewrite, '[Routing] vercel.json routes SPA fallbacks to /index.html');
    } catch (e: any) {
      assert(false, '[Config] vercel.json is valid JSON', e.message);
    }
  }

  // 2. Check Static Assets & Serverless Bundle
  const faviconIcoPath = path.join(process.cwd(), 'public', 'favicon.ico');
  const faviconSvgPath = path.join(process.cwd(), 'public', 'favicon.svg');
  const apiIndexPath = path.join(process.cwd(), 'api', 'index.js');
  assert(fs.existsSync(faviconIcoPath), '[Static Assets] public/favicon.ico exists and is non-empty');
  assert(fs.existsSync(faviconSvgPath), '[Static Assets] public/favicon.svg exists and is non-empty');
  assert(fs.existsSync(apiIndexPath), '[Serverless Bundle] api/index.js exists and is generated by build');

  if (fs.existsSync(apiIndexPath)) {
    const apiIndexContent = fs.readFileSync(apiIndexPath, 'utf-8');
    assert(!apiIndexContent.includes('from "../server/appFactory"'), '[Bundle Invariant] api/index.js inlines server/appFactory with no unbundled relative imports');
    assert(!apiIndexContent.includes("from '../server/appFactory'"), '[Bundle Invariant] api/index.js has no relative module paths');
  }

  // 3. Test Vercel Serverless Function Invocations via actual HTTP server
  const server = http.createServer((req, res) => {
    handler(req as any, res as any);
  });

  await new Promise<void>((resolve) => {
    server.listen(0, '127.0.0.1', () => resolve());
  });

  const address = server.address() as any;
  const baseUrl = `http://127.0.0.1:${address.port}`;

  try {
    // 1. Test /api/health
    const healthRes = await fetch(`${baseUrl}/api/health`);
    const healthData = await healthRes.json();
    assert(healthRes.status === 200 && healthData.status === 'ok', '[Serverless Route] GET /api/health returns 200 OK with JSON status');

    // 2. Test /api/admin/login (validation when body is missing)
    const loginRes = await fetch(`${baseUrl}/api/admin/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({})
    });
    const loginData = await loginRes.json();
    assert(loginRes.status === 400 && !!loginData.error, '[Serverless Route] POST /api/admin/login returns 400 with JSON error for empty body');

    // 3. Test /api/birthday/settings
    const bdayRes = await fetch(`${baseUrl}/api/birthday/settings`);
    const bdayData = await bdayRes.json();
    assert(bdayRes.status === 200 && bdayData.success === true, '[Serverless Route] GET /api/birthday/settings returns 200 OK with JSON settings');

    // 4. Test /api/audio/tracks
    const tracksRes = await fetch(`${baseUrl}/api/audio/tracks`);
    const tracksData = await tracksRes.json();
    assert(tracksRes.status === 200 && Array.isArray(tracksData.tracks), '[Serverless Route] GET /api/audio/tracks returns 200 with tracks array');

    // 5. Test /api/upload/imagekit-auth (Protected 401 without auth)
    const ikRes = await fetch(`${baseUrl}/api/upload/imagekit-auth`);
    assert(ikRes.status === 401, '[Serverless Route] GET /api/upload/imagekit-auth is protected with 401');

    // 6. Test /api/upload/audio (Protected 401 without auth)
    const uploadAudioRes = await fetch(`${baseUrl}/api/upload/audio`, { method: 'POST' });
    assert(uploadAudioRes.status === 401, '[Serverless Route] POST /api/upload/audio is protected with 401');

    // 7. Test /api/upload/media (Protected 401 without auth)
    const uploadMediaRes = await fetch(`${baseUrl}/api/upload/media`, { method: 'POST' });
    assert(uploadMediaRes.status === 401, '[Serverless Route] POST /api/upload/media is protected with 401');

    // 8. Test /api/upload/video (Protected 401 without auth)
    const uploadVideoRes = await fetch(`${baseUrl}/api/upload/video`, { method: 'POST' });
    assert(uploadVideoRes.status === 401, '[Serverless Route] POST /api/upload/video is protected with 401');

    // 9. Test /api/upload/image (Protected 401 without auth)
    const uploadImageRes = await fetch(`${baseUrl}/api/upload/image`, { method: 'POST' });
    assert(uploadImageRes.status === 401, '[Serverless Route] POST /api/upload/image is protected with 401');

    // 10. Test /api/audio/tracks/:id DELETE (Protected 401 without auth)
    const deleteTrackRes = await fetch(`${baseUrl}/api/audio/tracks/track-123`, { method: 'DELETE' });
    assert(deleteTrackRes.status === 401, '[Serverless Route] DELETE /api/audio/tracks/:id is protected with 401');

    // 11. Test nonexistent /api/unknown
    const notFoundRes = await fetch(`${baseUrl}/api/unknown-endpoint-test`);
    const notFoundData = await notFoundRes.json();
    assert(notFoundRes.status === 404 && !!notFoundData.error, '[Serverless Route] Nonexistent /api/* route returns JSON 404');

    // 12. Test direct route (stripped /api)
    const strippedHealthRes = await fetch(`${baseUrl}/health`);
    const strippedHealthData = await strippedHealthRes.json();
    assert(strippedHealthRes.status === 200 && strippedHealthData.status === 'ok', '[Serverless Route] Stripped prefix /health also succeeds');

  } finally {
    server.close();
  }

  console.log('============================================================');
  console.log(`Total Deployment Tests: ${passed + failed} | Passed: ${passed} | Failed: ${failed}`);
  console.log('============================================================\n');

  if (failed > 0) {
    process.exit(1);
  }
}

runVercelDeploymentTests().catch((err) => {
  console.error('Fatal test error:', err);
  process.exit(1);
});
